# GBA platform: devkitARM toolchain. Generated by Claude.

PREFIX  := arm-none-eabi-
CC      := $(PREFIX)gcc
OBJCOPY := $(PREFIX)objcopy
GBAFIX  := gbafix

ARCH             := -mcpu=arm7tdmi -mtune=arm7tdmi -mthumb -mthumb-interwork
PLATFORM_CFLAGS  := $(ARCH) -O2 -ffreestanding -Wall -Wextra
PLATFORM_ASFLAGS := $(ARCH)
PLATFORM_LDFLAGS := $(ARCH) -nostartfiles -nostdlib -T $(PLATFORM_DIR)/gba.ld -Wl,-Map,$(BUILD_DIR)/$(TARGET).map -lgcc

OUTPUT := $(BUILD_DIR)/$(TARGET).gba

# elf -> raw binary -> fix header
$(OUTPUT): $(ELF)
	@rm -f $@
	$(OBJCOPY) -v -O binary $< $@
	$(GBAFIX) $@
